services:
  - type: web
    name: stel-docs-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_API_KEY
        sync: false  # You'll set this manually in Render dashboard
    disk:
      name: stel-docs-data
      mountPath: /opt/render/project/src
      sizeGB: 1 