services:
  - type: web
    name: stel-docs-ai
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && pip install gunicorn && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: python manage.py runserver 0.0.0.0:$PORT
          envVars:
        - key: DEBUG
          value: True
        - key: SECRET_KEY
          generateValue: true
        - key: GOOGLE_API_KEY
          sync: false  # You'll set this manually in Render dashboard
    disk:
      name: stel-docs-data
      mountPath: /opt/render/project/src
      sizeGB: 1 